apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-6ist
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dmxi-tenant/rhtap-demo-app/hacbs-test-project-6ist@sha256:73039681e68b3bb9143309d91da4edc202e2270ed9b0b5ef71459f2cd584a4dd
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
