apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-6ist
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-6ist
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-6ist
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-6ist
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-6ist
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dmxi-tenant/rhtap-demo-app/hacbs-test-project-6ist@sha256:73039681e68b3bb9143309d91da4edc202e2270ed9b0b5ef71459f2cd584a4dd
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
